package shortestpath.pathfinder;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.BeforeClass;
import org.junit.Test;

/**
 * Regression tests for the bundled collision-map.zip resource.
 *
 * The collision map is regenerated by running the dumper in
 * collision-map-update/CollisionMapDumper.java. These tests lock down the
 * walkability of tiles around historically problematic locations so that
 * future regenerations do not silently regress them.
 *
 * Each tile encodes two flags (north/east); south and west are derived from
 * the neighbouring tile (see {@link CollisionMap}). A flag of {@code true}
 * means the player can move through that side; {@code false} is blocked.
 */
public class CollisionMapRegressionTest
{
	private static CollisionMap map;

	@BeforeClass
	public static void loadMap()
	{
		map = new CollisionMap(SplitFlagMap.fromResources());
	}

	private static void assertOpen(int x, int y, int z)
	{
		String tag = String.format("(%d,%d,%d)", x, y, z);
		assertTrue(tag + " expected to have at least one open neighbour",
			map.n(x, y, z) || map.e(x, y, z) || map.s(x, y, z) || map.w(x, y, z));
	}

	private static void assertWalkable(int x, int y, int z)
	{
		String tag = String.format("(%d,%d,%d)", x, y, z);
		assertTrue(tag + " north should be walkable", map.n(x, y, z));
		assertTrue(tag + " east should be walkable", map.e(x, y, z));
		assertTrue(tag + " south should be walkable", map.s(x, y, z));
		assertTrue(tag + " west should be walkable", map.w(x, y, z));
	}

	// ---------------------------------------------------------------------
	// Sanity: well-known fully-walkable plaza tiles should all be open.
	// These guard against a regenerated zip being completely empty/corrupt.
	// ---------------------------------------------------------------------

	@Test
	public void grandExchangeCentralTilesHaveOpenNeighbours()
	{
		// Centre of the Grand Exchange — booth clerks block some sides, but
		// every central tile must have at least one open neighbour.
		assertOpen(3164, 3486, 0);
		assertOpen(3164, 3487, 0);
		assertOpen(3165, 3486, 0);
	}

	@Test
	public void lumbridgeCourtyardIsFullyWalkable()
	{
		assertWalkable(3222, 3218, 0);
		assertWalkable(3222, 3219, 0);
	}

	@Test
	public void varrockSquareIsFullyWalkable()
	{
		assertWalkable(3213, 3424, 0);
		assertWalkable(3214, 3424, 0);
	}

	// ---------------------------------------------------------------------
	// Known-blocked locations (sanity check for true negatives).
	// ---------------------------------------------------------------------

	@Test
	public void deepWaterIsBlocked()
	{
		// Open ocean south-west of Catherby — should be entirely blocked.
		int x = 2780, y = 3400, z = 0;
		assertFalse(map.n(x, y, z));
		assertFalse(map.e(x, y, z));
		assertFalse(map.s(x, y, z));
		assertFalse(map.w(x, y, z));
	}

	// ---------------------------------------------------------------------
	// Issue #270 — Death Plateau approach.
	// The "invisible wall" object 38848 stands across the route up to Death
	// Plateau. It is genuinely a wall in the engine (see Duel Arena below),
	// so the dumper marks it as BLOCKED. Reaching the plateau in-game uses an
	// elevation/stairs route that should be expressed as a transport entry in
	// src/main/resources/transports/, NOT by relaxing the wall in the dumper.
	// This test locks down that the wall stays blocking on the dumper side.
	// ---------------------------------------------------------------------

	@Test
	public void deathPlateauApproachWallIsBlocked()
	{
		// Tile immediately south of the 38848 wall row at the Burthorpe entry
		// to Death Plateau — should not step north through the wall.
		assertFalse("Death Plateau invisible wall must block north step",
			map.n(2895, 3619, 0));
	}

	// ---------------------------------------------------------------------
	// Issue #233 — Fossil Island hunter footprints used to wrongly block
	// the Volcanic Mine area trail tiles.
	// ---------------------------------------------------------------------

	@Test
	public void fossilIslandHunterTrailIsWalkable()
	{
		// Sample tile on the Fossil Island hunter trail. Prior to the
		// 31303–31419 exclusion these were blocked by decorative footprints.
		int x = 3700, y = 3870, z = 0;
		assertTrue("Fossil Island hunter trail east should be open",
			map.e(x, y, z));
	}

	// ---------------------------------------------------------------------
	// Issue #339 / #465 — Duel Arena back wall.
	// The invisible wall (object 38848) at the rear of the old Duel Arena
	// should remain blocking; players cannot drop off the back of the arena.
	// ---------------------------------------------------------------------

	@Test
	public void duelArenaBackWallIsBlocked()
	{
		// Just inside the back wall — should not be able to step north.
		// (3320, 3228) is outside the arena footprint (false on all sides).
		int x = 3320, y = 3228, z = 0;
		assertFalse("Duel Arena back wall north step", map.n(x, y, z));
		assertFalse("Duel Arena back wall east step", map.e(x, y, z));
	}

	// ---------------------------------------------------------------------
	// Varrock Palace trellis: with no transport
	// configured the only crossing is via the trellis object, so adjacent
	// tiles should not be directly connected through the wall.
	// ---------------------------------------------------------------------

	@Test
	public void varrockPalaceTrellisWallIsPresent()
	{
		// (3228, 3471) is the wall tile; there should be no direct n/s
		// connection through it on plane 0.
		int x = 3228;
		// Trellis south side cannot step north into the wall tile.
		assertFalse("south of trellis should not step north through wall",
			map.n(x, 3470, 0));
		// Wall tile itself cannot step south back out the same direction.
		assertFalse("trellis wall tile should not step south", map.s(x, 3471, 0));
	}

	// ---------------------------------------------------------------------
	// Smoke: every region in the bundled zip should successfully load and
	// have a non-zero plane count when present.
	// ---------------------------------------------------------------------

	@Test
	public void mapLoadsWithExpectedExtents()
	{
		SplitFlagMap.RegionExtent extents = SplitFlagMap.getRegionExtents();
		assertTrue("region extents min x should be sane", extents.getMinX() >= 0);
		assertTrue("region extents min y should be sane", extents.getMinY() >= 0);
		assertTrue("region extents max x should be sane", extents.getMaxX() < 200);
		assertTrue("region extents max y should be sane", extents.getMaxY() < 200);
		// Width and height must be positive.
		assertTrue(extents.getWidth() > 0);
		assertTrue(extents.getHeight() > 0);
	}

	@Test
	public void loadedRegionsHaveFourPlanes()
	{
		// Spot-check a populated region (Lumbridge, region 12850 -> 50_50)
		// reports the expected four planes. The dumper writes 8 bits per tile
		// across z=0..3, so plane count should be 4.
		int regionIndex = SplitFlagMap.packPosition(50, 50);
		// SplitFlagMap stores by internal index; reconstruct via collision lookup
		// instead. A non-blocked Lumbridge tile guarantees the region is loaded.
		assertOpen(3222, 3218, 0);
		assertEquals("Lumbridge tile has expected position pack",
			(50 & 0xFFFF) | ((50 & 0xFFFF) << 16), regionIndex);
	}

	// =====================================================================
	// Per-issue regression locks for the linked bug reports in PR #466.
	// Coordinates were derived by diffing the previous master
	// collision-map.zip against the regenerated one (see
	// scripts/compare_collision_maps.py); each test pins down the tile-edge
	// flips that the fix produced so a future map regeneration cannot
	// silently undo them.
	// =====================================================================

	// Issue #178 — Twilight Temple stairs.
	// The mapScene over-block left the entire temple interior unreachable.
	// After the fix the stair landings (1684, 3245..3248, 0) are walkable
	// and the staircase tile (1684, 3247, 0) has open neighbours so the
	// pathfinder can descend through it.
	@Test
	public void issue178TwilightTempleStairIsReachable()
	{
		// Stair landing tiles all have at least one open neighbour after
		// dropping the mapScene over-block (previously they were
		// fully-blocked four-edge cells).
		assertOpen(1683, 3247, 0);
		assertOpen(1684, 3247, 0);
		assertOpen(1685, 3247, 0);
		assertOpen(1684, 3248, 0);
		// Stair traversal: north step on the staircase row should be walkable.
		assertTrue("stair row (1683,3247) east step", map.e(1683, 3247, 0));
		assertTrue("stair row (1684,3247) north step", map.n(1684, 3247, 0));
		assertTrue("stair row (1684,3247) west step", map.w(1684, 3247, 0));
	}

	// Issue #190 — Mind altar hidden-object collision.
	// Object id 85 used to mark (2979, 3508, 0) as fully blocked. The fix
	// makes the tile walkable so the pathfinder no longer detours around it.
	@Test
	public void issue190MindAltarTileIsWalkable()
	{
		// Old map had all four edges blocked; new map opens N/S/W.
		assertTrue("(2979,3508) north should be open", map.n(2979, 3508, 0));
		assertTrue("(2979,3508) south should be open", map.s(2979, 3508, 0));
		assertTrue("(2979,3508) west should be open", map.w(2979, 3508, 0));
	}

	// Issue #193 / #303 — Auburnvale bridge.
	// The bridge approach tiles (1435..1436, 3340..3344, 0) were entirely
	// blocked because the wooden railing walls carry a mapSceneID. The fix
	// reinterprets those walls as ordinary directional walls so the bridge
	// approach is walkable.
	@Test
	public void issue193AuburnvaleBridgeApproachIsWalkable()
	{
		// All five rows of the southern bridge approach should be open enough
		// for the pathfinder to step through.
		for (int y = 3340; y <= 3344; y++)
		{
			assertTrue("Auburnvale bridge approach (1435," + y + ") north",
				map.n(1435, y, 0));
			assertTrue("Auburnvale bridge approach (1435," + y + ") east",
				map.e(1435, y, 0));
		}
	}

	// Issue #270 — Death Plateau climb-rocks access.
	// The climb-rocks transport endpoints must both be walkable. The
	// invisible wall above them remains blocking (covered separately by
	// deathPlateauApproachWallIsBlocked).
	@Test
	public void issue270DeathPlateauClimbEndpointsAreWalkable()
	{
		assertOpen(2856, 3611, 0); // bottom-of-rocks tile
		assertOpen(2856, 3613, 0); // top-of-rocks tile
	}

	// Issue #313 — Rock north of Sophanem.
	// Region (59, 45) was heavily under-populated in the previous map (most
	// tiles fully blocked because the rock decoration carried a mapScene id
	// over the whole footprint). The fix lets the dumper emit real wall flags
	// for the area so the rock is just a single obstacle rather than a wall
	// of blocked terrain.
	@Test
	public void issue313SophanemRegionIsPopulated()
	{
		// Centre of the rock area, well clear of the rock itself.
		assertWalkable(3779, 2901, 0);
		assertWalkable(3781, 2901, 0);
	}

	// Issue #203 — Dwarf Cannon damaged railings.
	// The 17 wall variants 15589-15605 carry wallOrDoor=1 so the dumper
	// otherwise treats them as passable doors. All variants are excluded so
	// the railings around the Dwarf Cannon camp block ordinary movement;
	// the quest itself crosses them via an inspect action, not pathfinding.
	@Test
	public void issue203DwarfCannonRailingsBlock()
	{
		// North-facing railings along the camp's southern fence.
		assertFalse("(2566,3455,0) N should be blocked", map.n(2566, 3455, 0));
		assertFalse("(2567,3455,0) N should be blocked", map.n(2567, 3455, 0));
		assertFalse("(2568,3455,0) N should be blocked", map.n(2568, 3455, 0));
		assertFalse("(2569,3455,0) N should be blocked", map.n(2569, 3455, 0));
		// East-facing railings along the camp's western fence.
		assertFalse("(2554,3473,0) E should be blocked", map.e(2554, 3473, 0));
		assertFalse("(2554,3474,0) E should be blocked", map.e(2554, 3474, 0));
		assertFalse("(2554,3475,0) E should be blocked", map.e(2554, 3475, 0));
	}
}
