package shortestpath.accounts;

import net.runelite.api.gameval.VarPlayerID;
import net.runelite.api.gameval.VarbitID;

/**
 * Something an account has unlocked that routing depends on and that is not a quest, diary,
 * spellbook or POH fact. Each sets one variable: a varbit to a value, or a bit in a
 * varplayer mask (quetzal platforms).
 */
public enum Unlock {
    FAIRY_RINGS(Group.TRANSPORT, Kind.VARBIT, VarbitID.FAIRY2_QUEENCURE_QUEST, 100),
    RAIDS_MOUNTAIN_GUIDE_TRAVEL(Group.TRANSPORT, Kind.VARBIT, VarbitID.RAIDS_GUIDE_TRAVEL_UNLOCK, 1),
    MET_AUBURN_MOUNTAIN_GUIDE(Group.TRANSPORT, Kind.VARBIT, VarbitID.MET_AUBURN_MOUNTAIN_GUIDE, 1),
    CORSAIR_COVE_RESOURCE_AREA(Group.TRANSPORT, Kind.VARBIT, VarbitID.CORSAIR_COVE_RESOURCE_ENTRY, 1),
    LOST_TRIBE_CELLAR_HOLE(Group.TRANSPORT, Kind.VARBIT, VarbitID.LOST_TRIBE_HOLE_2_DUG, 1),
    BARBARIAN_ASSAULT_TUTORIAL(Group.TRANSPORT, Kind.VARBIT, VarbitID.BARBASSAULT_ARENANEWB, 11),
    MUSEUM_KUDOS_153(Group.TRANSPORT, Kind.VARBIT, VarbitID.VM_KUDOS, 153),
    BARBARIAN_FIREMAKING_TRAINING(Group.TRANSPORT, Kind.VARBIT, VarbitID.BRUT_FIRE, 2),
    FENKENSTRAIN_BRIDGE_NORTH(Group.TRANSPORT, Kind.VARBIT, VarbitID.FENK_BUILT_BRIDGE_NORTH, 2),
    FENKENSTRAIN_BRIDGE_SOUTH(Group.TRANSPORT, Kind.VARBIT, VarbitID.FENK_BUILT_BRIDGE_SOUTH, 2),
    KARAMJA_DUNGEON_BACKDOOR(Group.TRANSPORT, Kind.VARBIT, VarbitID.KARAM_DUNGEON_BACKDOOR, 1),
    OBSERVATORY_SHORTCUT_ROPE(Group.TRANSPORT, Kind.VARBIT, VarbitID.OBSERVATORY_SHORTCUT_ROPE, 1),
    /** The Dwarven Mine crevice shortcut; the game tracks it in a varbit named {@code LUMBRIDGE_MED_COUNT}. */
    DWARVEN_MINE_CREVICE(Group.TRANSPORT, Kind.VARBIT, VarbitID.LUMBRIDGE_MED_COUNT, 1),
    HOSIDIUS_DUNGEON_WEST_DOOR(Group.TRANSPORT, Kind.VARBIT, VarbitID.HOSDUN_WEST_DOOR_STATUS, 1),
    HOSIDIUS_DUNGEON_EAST_DOOR(Group.TRANSPORT, Kind.VARBIT, VarbitID.HOSDUN_EAST_DOOR_STATUS, 1),
    DARKMEYER_INNER_SHORTCUT(Group.TRANSPORT, Kind.VARBIT, VarbitID.DARKM_SHORTCUT_INNER, 1),
    DARKMEYER_OUTER_SHORTCUT(Group.TRANSPORT, Kind.VARBIT, VarbitID.DARKM_SHORTCUT_OUTER, 1),
    PHARAOHS_SCEPTRE_NECROPOLIS(Group.TRANSPORT, Kind.VARBIT, VarbitID.PHARAOHS_SCEPTRE_NECROPOLIS, 1),
    COLOSSEUM_WAVE_NINE(Group.TRANSPORT, Kind.VARBIT, VarbitID.COLOSSEUM_HIGHEST_WAVE, 9),
    SINS_OF_THE_FATHER_SLEPE_BOAT(Group.TRANSPORT, Kind.VARBIT, VarbitID.MYQ5, 88),
    LAND_OF_THE_GOBLINS_YU_BIUSK(Group.TRANSPORT, Kind.VARBIT, VarbitID.LOTG, 50),
    /** The Architectural Alliance reward, which RuneLite's {@code Quest} does not list. */
    ARCHITECTURAL_ALLIANCE(Group.TRANSPORT, Kind.VARBIT, VarbitID.ARCQUEST_REWARD, 1),
    /** The Tale of the Righteous reward, which RuneLite's {@code Quest} does not list. */
    TALE_OF_THE_RIGHTEOUS(Group.TRANSPORT, Kind.VARBIT, VarbitID.SHAYZIENQUEST_REWARD, 1),

    BOOK_OF_SCROLLS_NARDAH(Group.BOOK_OF_SCROLLS, Kind.VARBIT, VarbitID.BOOKOFSCROLLS_NARDAH, 1),
    BOOK_OF_SCROLLS_DIGSITE(Group.BOOK_OF_SCROLLS, Kind.VARBIT, VarbitID.BOOKOFSCROLLS_DIGSITE, 1),
    BOOK_OF_SCROLLS_FELDIP(Group.BOOK_OF_SCROLLS, Kind.VARBIT, VarbitID.BOOKOFSCROLLS_FELDIP, 1),
    BOOK_OF_SCROLLS_LUNAR_ISLE(Group.BOOK_OF_SCROLLS, Kind.VARBIT, VarbitID.BOOKOFSCROLLS_LUNARISLE, 1),
    BOOK_OF_SCROLLS_MORTTON(Group.BOOK_OF_SCROLLS, Kind.VARBIT, VarbitID.BOOKOFSCROLLS_MORTTON, 1),
    BOOK_OF_SCROLLS_PEST_CONTROL(Group.BOOK_OF_SCROLLS, Kind.VARBIT, VarbitID.BOOKOFSCROLLS_PESTCONTROL, 1),
    BOOK_OF_SCROLLS_PISCATORIS(Group.BOOK_OF_SCROLLS, Kind.VARBIT, VarbitID.BOOKOFSCROLLS_PISCATORIS, 1),
    BOOK_OF_SCROLLS_TAI_BWO(Group.BOOK_OF_SCROLLS, Kind.VARBIT, VarbitID.BOOKOFSCROLLS_TAIBWO, 1),
    BOOK_OF_SCROLLS_ELF(Group.BOOK_OF_SCROLLS, Kind.VARBIT, VarbitID.BOOKOFSCROLLS_ELF, 1),
    BOOK_OF_SCROLLS_MOS_LE_HARMLESS(Group.BOOK_OF_SCROLLS, Kind.VARBIT, VarbitID.BOOKOFSCROLLS_MOSLES, 1),
    BOOK_OF_SCROLLS_LUMBERYARD(Group.BOOK_OF_SCROLLS, Kind.VARBIT, VarbitID.BOOKOFSCROLLS_LUMBERYARD, 1),
    BOOK_OF_SCROLLS_ZUL_ANDRA(Group.BOOK_OF_SCROLLS, Kind.VARBIT, VarbitID.BOOKOFSCROLLS_ZULANDRA, 1),
    BOOK_OF_SCROLLS_CERBERUS(Group.BOOK_OF_SCROLLS, Kind.VARBIT, VarbitID.BOOKOFSCROLLS_CERBERUS, 1),
    BOOK_OF_SCROLLS_REVENANTS(Group.BOOK_OF_SCROLLS, Kind.VARBIT, VarbitID.BOOKOFSCROLLS_REVENANTS, 1),
    BOOK_OF_SCROLLS_WATSON(Group.BOOK_OF_SCROLLS, Kind.VARBIT, VarbitID.BOOKOFSCROLLS_WATSON_LOWBITS, 1),

    PENDANT_OF_ATES_DARKFROST(Group.PENDANT_OF_ATES, Kind.VARBIT, VarbitID.PENDANT_OF_ATES_DARKFROST_FOUND, 1),
    PENDANT_OF_ATES_TWILIGHT(Group.PENDANT_OF_ATES, Kind.VARBIT, VarbitID.PENDANT_OF_ATES_TWILIGHT_FOUND, 1),
    PENDANT_OF_ATES_RALOS(Group.PENDANT_OF_ATES, Kind.VARBIT, VarbitID.PENDANT_OF_ATES_RALOS_FOUND, 1),
    PENDANT_OF_ATES_ALDARIN(Group.PENDANT_OF_ATES, Kind.VARBIT, VarbitID.PENDANT_OF_ATES_ALDARIN_FOUND, 1),

    BALLOON_ENTRANA(Group.HOT_AIR_BALLOON, Kind.VARBIT, VarbitID.ZEP_MULTI_BASKET, 2),
    BALLOON_TAVERLEY(Group.HOT_AIR_BALLOON, Kind.VARBIT, VarbitID.ZEP_MULTI_PICCARD, 2),
    BALLOON_CASTLE_WARS(Group.HOT_AIR_BALLOON, Kind.VARBIT, VarbitID.ZEP_MULTI_CAST, 1),
    BALLOON_GRAND_TREE(Group.HOT_AIR_BALLOON, Kind.VARBIT, VarbitID.ZEP_MULTI_GNO, 1),
    BALLOON_CRAFTING_GUILD(Group.HOT_AIR_BALLOON, Kind.VARBIT, VarbitID.ZEP_MULTI_CRAFT, 1),
    BALLOON_VARROCK(Group.HOT_AIR_BALLOON, Kind.VARBIT, VarbitID.ZEP_MULTI_VARR, 1),

    CATACOMBS_FORTHOS_DUNGEON(Group.CATACOMBS, Kind.VARBIT, VarbitID.CATA_HOLE1, 1),
    CATACOMBS_SURFACE_ENTRANCES(Group.CATACOMBS, Kind.VARBIT, VarbitID.CATA_HOLE2, 1),
    CATACOMBS_GIANTS_DEN(Group.CATACOMBS, Kind.VARBIT, VarbitID.CATA_HOLE_GIANTS_DEN, 1),

    QUETZAL_CAM_TORUM(Group.QUETZAL, Kind.VARPLAYER_BIT, VarPlayerID.QUETZALS_UNLOCKED, 32),
    QUETZAL_COLOSSAL_WYRM_REMAINS(Group.QUETZAL, Kind.VARPLAYER_BIT, VarPlayerID.QUETZALS_UNLOCKED, 64),
    QUETZAL_OUTER_FORTIS(Group.QUETZAL, Kind.VARPLAYER_BIT, VarPlayerID.QUETZALS_UNLOCKED, 128),
    QUETZAL_FORTIS_COLOSSEUM(Group.QUETZAL, Kind.VARPLAYER_BIT, VarPlayerID.QUETZALS_UNLOCKED, 256),
    QUETZAL_SALVAGER_OVERLOOK(Group.QUETZAL, Kind.VARPLAYER_BIT, VarPlayerID.QUETZALS_UNLOCKED, 2048),
    QUETZAL_KASTORI(Group.QUETZAL, Kind.VARPLAYER_BIT, VarPlayerID.QUETZALS_UNLOCKED, 16384),

    ROWBOAT_VATRACHOS(Group.ROWBOAT, Kind.VARBIT, VarbitID.AMENITY_ROWBOAT_VATRACHOS, 1),
    ROWBOAT_ANGLERS(Group.ROWBOAT, Kind.VARBIT, VarbitID.AMENITY_ROWBOAT_ANGLERS, 1),
    ROWBOAT_SOUL_TEAR(Group.ROWBOAT, Kind.VARBIT, VarbitID.AMENITY_ROWBOAT_SOUL_TEAR, 1),
    ROWBOAT_YNYSDAIL(Group.ROWBOAT, Kind.VARBIT, VarbitID.AMENITY_ROWBOAT_YNYSDAIL, 1),
    ROWBOAT_BUCCANEERS(Group.ROWBOAT, Kind.VARBIT, VarbitID.AMENITY_ROWBOAT_BUCCANEERS, 1),

    RESPAWN_FALADOR(Group.RESPAWN, Kind.VARBIT, VarbitID.FALADOR_SPAWN, 1),
    RESPAWN_CAMELOT(Group.RESPAWN, Kind.VARBIT, VarbitID.CAMELOT_SPAWN, 1),
    RESPAWN_EDGEVILLE(Group.RESPAWN, Kind.VARBIT, VarbitID.EDGEVILLE_SPAWN, 1),
    RESPAWN_FEROX_ENCLAVE(Group.RESPAWN, Kind.VARBIT, VarbitID.WILDERNESS_SPAWN, 1),
    RESPAWN_KOUREND_CASTLE(Group.RESPAWN, Kind.VARBIT, VarbitID.KOUREND_SPAWN, 1),
    RESPAWN_CIVITAS_ILLA_FORTIS(Group.RESPAWN, Kind.VARBIT, VarbitID.CIVITAS_SPAWN, 1);

    /** How an editor groups unlocks. */
    public enum Group { TRANSPORT, BOOK_OF_SCROLLS, PENDANT_OF_ATES, HOT_AIR_BALLOON, CATACOMBS, QUETZAL, ROWBOAT, RESPAWN }

    enum Kind { VARBIT, VARPLAYER_BIT }

    public final Group group;
    final Kind kind;
    final int id;
    /** The variable's value when unlocked, or the bit for {@link Kind#VARPLAYER_BIT}. */
    final int value;

    Unlock(Group group, Kind kind, int id, int value) {
        this.group = group;
        this.kind = kind;
        this.id = id;
        this.value = value;
    }
}
