package shortestpath.accounts.canonical;

import net.runelite.api.ItemID;
import java.util.LinkedHashMap;
import java.util.Map;

/** Concrete owned items, still authored with RuneLite's item identifiers. */
final class CanonicalItems {
    private CanonicalItems() { }

    static Map<Integer, Integer> runePouch() {
        return items(10_000, ItemID.FIRE_RUNE, ItemID.WATER_RUNE, ItemID.AIR_RUNE, ItemID.LAW_RUNE);
    }

    static Map<Integer, Integer> earlyInventory() {
        Map<Integer, Integer> result = items(1, ItemID.DRAMEN_STAFF, ItemID.AMULET_OF_GLORY, ItemID.RING_OF_DUELING8,
            ItemID.GAMES_NECKLACE8, ItemID.TELEPORT_TO_HOUSE);
        result.put(ItemID.COINS_995, 100_000);
        return result;
    }

    static Map<Integer, Integer> midInventory() {
        Map<Integer, Integer> result = items(1, ItemID.DRAMEN_STAFF, ItemID.AMULET_OF_GLORY, ItemID.RING_OF_DUELING8,
            ItemID.GAMES_NECKLACE8, ItemID.TELEPORT_TO_HOUSE, ItemID.DIGSITE_PENDANT_1,
            ItemID.SLAYER_RING_8, ItemID.BASIC_QUETZAL_WHISTLE);
        result.put(ItemID.COINS_995, 1_000_000);
        return result;
    }

    static Map<Integer, Integer> endInventory() {
        Map<Integer, Integer> result = items(1, ItemID.AMULET_OF_GLORY, ItemID.RING_OF_DUELING8, ItemID.TELEPORT_TO_HOUSE,
            ItemID.QUEST_POINT_CAPE);
        result.put(ItemID.COINS_995, 5_000_000);
        return result;
    }

    static Map<Integer, Integer> maxedInventory() {
        Map<Integer, Integer> result = items(1, ItemID.TELEPORT_TO_HOUSE, ItemID.ACHIEVEMENT_DIARY_CAPE_T, ItemID.MAX_CAPE);
        result.put(ItemID.COINS_995, 10_000_000);
        return result;
    }

    static Map<Integer, Integer> earlyBank() {
        return items(1_000, ItemID.DRAMEN_STAFF, ItemID.COINS_995, ItemID.AMULET_OF_GLORY,
            ItemID.RING_OF_DUELING8, ItemID.GAMES_NECKLACE8, ItemID.TELEPORT_TO_HOUSE,
            ItemID.SKILLS_NECKLACE4, ItemID.COMBAT_BRACELET4, ItemID.RING_OF_WEALTH_5,
            ItemID.NECKLACE_OF_PASSAGE5);
    }

    static Map<Integer, Integer> midBank() {
        return items(1_000,
            ItemID.FIRE_RUNE, ItemID.WATER_RUNE, ItemID.AIR_RUNE, ItemID.EARTH_RUNE, ItemID.NATURE_RUNE,
            ItemID.LAW_RUNE, ItemID.DRAMEN_STAFF, ItemID.CROSSBOW, ItemID.ROPE, ItemID.MACHETE,
            ItemID.COINS_995, ItemID.BRONZE_PICKAXE, ItemID.BRONZE_AXE, ItemID.SHANTAY_PASS,
            ItemID.RING_OF_DUELING8, ItemID.GAMES_NECKLACE8, ItemID.ECTOPHIAL, ItemID.CAMULET,
            ItemID.VARROCK_TELEPORT, ItemID.LUMBRIDGE_TELEPORT, ItemID.FALADOR_TELEPORT,
            ItemID.CAMELOT_TELEPORT, ItemID.ARDOUGNE_TELEPORT, ItemID.WATCHTOWER_TELEPORT,
            ItemID.TELEPORT_TO_HOUSE, ItemID.MITH_GRAPPLE, ItemID.KARAMJA_GLOVES_3,
            ItemID.DIGSITE_PENDANT_5, ItemID.SLAYER_RING_8, ItemID.SKILLS_NECKLACE6,
            ItemID.COMBAT_BRACELET6, ItemID.AMULET_OF_GLORY6, ItemID.RING_OF_WEALTH_5,
            ItemID.NARDAH_TELEPORT, ItemID.DIGSITE_TELEPORT, ItemID.FELDIP_HILLS_TELEPORT,
            ItemID.MORTTON_TELEPORT, ItemID.PEST_CONTROL_TELEPORT, ItemID.TAI_BWO_WANNAI_TELEPORT,
            ItemID.IORWERTH_CAMP_TELEPORT, ItemID.ZULANDRA_TELEPORT, ItemID.WILDERNESS_SWORD_3,
            ItemID.MORYTANIA_LEGS_3, ItemID.ARDOUGNE_CLOAK_3, ItemID.EXPLORERS_RING_3,
            ItemID.FREMENNIK_SEA_BOOTS_3, ItemID.DESERT_AMULET_3, ItemID.KANDARIN_HEADGEAR_3,
            ItemID.WESTERN_BANNER_3, ItemID.XERICS_TALISMAN, ItemID.CHRONICLE,
            ItemID.ROYAL_SEED_POD, ItemID.NECKLACE_OF_PASSAGE5, ItemID.BURNING_AMULET5,
            ItemID.MASTER_SCROLL_BOOK, ItemID.KHAREDSTS_MEMOIRS, ItemID.DRAKANS_MEDALLION,
            ItemID.ICY_BASALT, ItemID.STONY_BASALT, ItemID.RADAS_BLESSING_3,
            ItemID.ETERNAL_TELEPORT_CRYSTAL, ItemID.BOOK_OF_THE_DEAD, ItemID.ENHANCED_QUETZAL_WHISTLE,
            ItemID.PENDANT_OF_ATES, ItemID.SAILORS_AMULET);
    }

    static Map<Integer, Integer> endBank() {
        Map<Integer, Integer> result = midBank();
        result.remove(ItemID.KARAMJA_GLOVES_3); result.put(ItemID.KARAMJA_GLOVES_4, 1_000);
        result.remove(ItemID.WILDERNESS_SWORD_3); result.put(ItemID.WILDERNESS_SWORD_4, 1_000);
        result.remove(ItemID.MORYTANIA_LEGS_3); result.put(ItemID.MORYTANIA_LEGS_4, 1_000);
        result.remove(ItemID.ARDOUGNE_CLOAK_3); result.put(ItemID.ARDOUGNE_CLOAK_4, 1_000);
        result.remove(ItemID.EXPLORERS_RING_3); result.put(ItemID.EXPLORERS_RING_4, 1_000);
        result.remove(ItemID.FREMENNIK_SEA_BOOTS_3); result.put(ItemID.FREMENNIK_SEA_BOOTS_4, 1_000);
        result.remove(ItemID.DESERT_AMULET_3); result.put(ItemID.DESERT_AMULET_4, 1_000);
        result.remove(ItemID.KANDARIN_HEADGEAR_3); result.put(ItemID.KANDARIN_HEADGEAR_4, 1_000);
        result.remove(ItemID.WESTERN_BANNER_3); result.put(ItemID.WESTERN_BANNER_4, 1_000);
        result.remove(ItemID.RADAS_BLESSING_3); result.put(ItemID.RADAS_BLESSING_4, 1_000);
        result.put(ItemID.DIGSITE_PENDANT_5, 1_000);
        result.put(ItemID.LUNAR_ISLE_TELEPORT, 1_000); result.put(ItemID.PISCATORIS_TELEPORT, 1_000);
        result.put(ItemID.MOS_LEHARMLESS_TELEPORT, 1_000); result.put(ItemID.LUMBERYARD_TELEPORT, 1_000);
        result.put(ItemID.SLAYER_RING_ETERNAL, 1_000); result.put(ItemID.ENCHANTED_LYREI, 1_000);
        result.put(ItemID.RING_OF_THE_ELEMENTS_26818, 1_000); result.put(ItemID.PHARAOHS_SCEPTRE_26948, 1_000);
        result.put(ItemID.RING_OF_SHADOWS, 1_000); result.put(ItemID.PERFECTED_QUETZAL_WHISTLE, 1_000);
        result.remove(ItemID.ENHANCED_QUETZAL_WHISTLE);
        result.put(ItemID.COWBELL_AMULET_33104, 1_000);
        return result;
    }

    static Map<Integer, Integer> maxedBank() {
        Map<Integer, Integer> result = endBank();
        result.put(ItemID.WESTERN_BANNER_3, 1_000);
        result.put(ItemID.RADAS_BLESSING_3, 1_000);
        int[] extra = {
            ItemID.KEY_298, ItemID.MIND_RUNE, ItemID.BLOOD_RUNE, ItemID.SOUL_RUNE, ItemID.LOCKPICK,
            ItemID.MAZE_KEY, ItemID.KEY_1543, ItemID.DUSTY_KEY, ItemID.AMULET_OF_GLORY1,
            ItemID.AMULET_OF_GLORY2, ItemID.AMULET_OF_GLORY3, ItemID.AMULET_OF_GLORY4, ItemID.BROWN_APRON,
            ItemID.BANANA, ItemID.SKAVID_MAP, ItemID.RING_OF_DUELING7, ItemID.RING_OF_DUELING6,
            ItemID.RING_OF_DUELING5, ItemID.RING_OF_DUELING4, ItemID.RING_OF_DUELING3,
            ItemID.RING_OF_DUELING2, ItemID.RING_OF_DUELING1, ItemID.BATTERED_KEY, ItemID.CLIMBING_BOOTS,
            ItemID.ENCHANTED_LYRE1, ItemID.GAMES_NECKLACE7, ItemID.GAMES_NECKLACE6, ItemID.GAMES_NECKLACE5,
            ItemID.GAMES_NECKLACE4, ItemID.GAMES_NECKLACE3, ItemID.GAMES_NECKLACE2, ItemID.GAMES_NECKLACE1,
            ItemID.GLOWING_FUNGUS, ItemID.SLED_4084, ItemID.ECTOPHIAL_4252, ItemID.ECTOTOKEN,
            ItemID.STEEL_KEY_RING, ItemID.CASTLEWARS_HOOD, ItemID.CASTLEWARS_CLOAK, ItemID.GOLD_HELMET,
            ItemID.RING_OF_VISIBILITY, ItemID.TELEPORT_CRYSTAL_4, ItemID.TELEPORT_CRYSTAL_3,
            ItemID.TELEPORT_CRYSTAL_2, ItemID.TELEPORT_CRYSTAL_1, ItemID.ENCHANTED_LYRE2,
            ItemID.ENCHANTED_LYRE3, ItemID.ENCHANTED_LYRE4, ItemID.SKULL_SCEPTRE, ItemID.ASTRAL_RUNE,
            ItemID.GRAND_SEED_POD, ItemID.STRENGTH_CAPE, ItemID.STRENGTH_CAPET, ItemID.CRAFTING_CAPE,
            ItemID.CRAFTING_CAPET, ItemID.CONSTRUCT_CAPE, ItemID.CONSTRUCT_CAPET, ItemID.FISHING_CAPE,
            ItemID.FISHING_CAPET, ItemID.FARMING_CAPE, ItemID.FARMING_CAPET, ItemID.HUNTER_CAPE,
            ItemID.HUNTER_CAPET, ItemID.AMULET_OF_GLORY_T4, ItemID.AMULET_OF_GLORY_T3,
            ItemID.AMULET_OF_GLORY_T2, ItemID.AMULET_OF_GLORY_T1, ItemID.SKILLS_NECKLACE4,
            ItemID.SKILLS_NECKLACE3, ItemID.SKILLS_NECKLACE2, ItemID.SKILLS_NECKLACE1,
            ItemID.COMBAT_BRACELET4, ItemID.COMBAT_BRACELET3, ItemID.COMBAT_BRACELET2,
            ItemID.COMBAT_BRACELET1, ItemID.DIGSITE_PENDANT_1, ItemID.DIGSITE_PENDANT_2,
            ItemID.DIGSITE_PENDANT_3, ItemID.DIGSITE_PENDANT_4, ItemID.RIMMINGTON_TELEPORT,
            ItemID.TAVERLEY_TELEPORT, ItemID.POLLNIVNEACH_TELEPORT, ItemID.RELLEKKA_TELEPORT,
            ItemID.BRIMHAVEN_TELEPORT, ItemID.YANILLE_TELEPORT, ItemID.TROLLHEIM_TELEPORT,
            ItemID.SLAYER_RING_7, ItemID.SLAYER_RING_6, ItemID.SLAYER_RING_5, ItemID.SLAYER_RING_4,
            ItemID.SLAYER_RING_3, ItemID.SLAYER_RING_2, ItemID.SLAYER_RING_1, ItemID.AMULET_OF_GLORY_T6,
            ItemID.AMULET_OF_GLORY_T5, ItemID.SKILLS_NECKLACE5, ItemID.COMBAT_BRACELET5,
            ItemID.AMULET_OF_GLORY5, ItemID.AMULET_OF_GLORY6, ItemID.RING_OF_WEALTH_4,
            ItemID.RING_OF_WEALTH_3, ItemID.RING_OF_WEALTH_2, ItemID.RING_OF_WEALTH_1,
            ItemID.ANNAKARL_TELEPORT, ItemID.CARRALLANGER_TELEPORT, ItemID.DAREEYAK_TELEPORT,
            ItemID.GHORROCK_TELEPORT, ItemID.KHARYRLL_TELEPORT, ItemID.LASSAR_TELEPORT,
            ItemID.PADDEWWA_TELEPORT, ItemID.SENNTISTEN_TELEPORT, ItemID.QUEST_POINT_CAPE_T,
            ItemID.ACHIEVEMENT_DIARY_CAPE_T, ItemID.ENCHANTED_LYRE5, ItemID.TELEPORT_CRYSTAL_5,
            ItemID.QUEST_POINT_CAPE, ItemID.KARAMJA_GLOVES_3, ItemID.WILDERNESS_SWORD_3,
            ItemID.MORYTANIA_LEGS_1, ItemID.MORYTANIA_LEGS_2, ItemID.MORYTANIA_LEGS_3, ItemID.ARDOUGNE_CLOAK_1,
            ItemID.ARDOUGNE_CLOAK_2, ItemID.ARDOUGNE_CLOAK_3, ItemID.EXPLORERS_RING_2, ItemID.EXPLORERS_RING_3,
            ItemID.FREMENNIK_SEA_BOOTS_1, ItemID.FREMENNIK_SEA_BOOTS_2, ItemID.FREMENNIK_SEA_BOOTS_3,
            ItemID.DESERT_AMULET_2, ItemID.DESERT_AMULET_3,
            ItemID.KANDARIN_HEADGEAR_3, ItemID.MUSIC_CAPE, ItemID.MUSIC_CAPET, ItemID.KEY_MASTER_TELEPORT,
            ItemID.MAX_HOOD, ItemID.MAX_CAPE_13342, ItemID.ACHIEVEMENT_DIARY_CAPE,
            ItemID.ARCEUUS_LIBRARY_TELEPORT, ItemID.DRAYNOR_MANOR_TELEPORT, ItemID.MIND_ALTAR_TELEPORT,
            ItemID.SALVE_GRAVEYARD_TELEPORT, ItemID.FENKENSTRAINS_CASTLE_TELEPORT,
            ItemID.WEST_ARDOUGNE_TELEPORT, ItemID.HARMONY_ISLAND_TELEPORT, ItemID.CEMETERY_TELEPORT,
            ItemID.BARROWS_TELEPORT, ItemID.APE_ATOLL_TELEPORT, ItemID.HOSIDIUS_TELEPORT,
            ItemID.AMULET_OF_ETERNAL_GLORY, ItemID.ARDOUGNE_MAX_CAPE, ItemID.RING_OF_WEALTH_I5,
            ItemID.RING_OF_WEALTH_I4, ItemID.RING_OF_WEALTH_I3, ItemID.RING_OF_WEALTH_I2,
            ItemID.RING_OF_WEALTH_I1, ItemID.NECKLACE_OF_PASSAGE4, ItemID.NECKLACE_OF_PASSAGE3,
            ItemID.NECKLACE_OF_PASSAGE2, ItemID.NECKLACE_OF_PASSAGE1, ItemID.BURNING_AMULET4,
            ItemID.BURNING_AMULET3, ItemID.BURNING_AMULET2, ItemID.BURNING_AMULET1, ItemID.SKULL_SCEPTRE_I,
            ItemID.VOLCANIC_MINE_TELEPORT, ItemID.REVENANT_CAVE_TELEPORT, ItemID.MYTHICAL_CAPE,
            ItemID.MYTHICAL_CAPE_22114, ItemID.RADAS_BLESSING_1, ItemID.RADAS_BLESSING_2,
            ItemID.RADAS_BLESSING_4,
            ItemID.BATTLEFRONT_TELEPORT, ItemID.WATSON_TELEPORT, ItemID.PRIFDDINAS_TELEPORT,
            ItemID.WILDERNESS_CRABS_TELEPORT, ItemID.HALLOWED_CRYSTAL_SHARD, ItemID.MYTHICAL_MAX_CAPE,
            ItemID.MOONCLAN_TELEPORT, ItemID.OURANIA_TELEPORT, ItemID.WATERBIRTH_TELEPORT,
            ItemID.BARBARIAN_TELEPORT, ItemID.KHAZARD_TELEPORT, ItemID.FISHING_GUILD_TELEPORT,
            ItemID.CATHERBY_TELEPORT, ItemID.ICE_PLATEAU_TELEPORT, ItemID.FAIRY_MUSHROOM,
            ItemID.AMULET_OF_THE_EYE, ItemID.RING_OF_SHADOWS_UNCHARGED, ItemID.BASIC_QUETZAL_WHISTLE,
            ItemID.ENHANCED_QUETZAL_WHISTLE, ItemID.PERFECTED_QUETZAL_WHISTLE, ItemID.PENDANT_OF_ATES,
            ItemID.BANKERS_BRIEFCASE, ItemID.GIANTSOUL_AMULET, ItemID.PERFECTED_QUETZAL_WHISTLEI,
            ItemID.EVIL_EYE, ItemID.MAP_OF_ALACRITY
        };
        for (int id : extra) result.put(id, 1_000);
        result.put(ItemID.MAX_CAPE, 2_000);
        return result;
    }

    private static Map<Integer, Integer> items(int quantity, int... ids) {
        Map<Integer, Integer> result = new LinkedHashMap<>();
        for (int id : ids) result.put(id, quantity);
        return result;
    }
}
